repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt -l -d
        language: system
        types: [go]
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.11.0
    hooks:
      - id: golangci-lint
